#Nombre del proyecto
spring.application.name=backend-GoGoMap

#Conexion a MySQL(Forzamos el uso de UTF-8)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/gogomap_db?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8}
spring.datasource.username=${DB_USERNAME:user}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Configuracion de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Configuracion JWT con Variables de Entorno (y valor de rescate por defecto)
app.jwt.secret=${JWT_SECRET:clave_secreta_por_defecto_para_desarrollo_local_de_32_caracteres_minimo}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:1440}


